### ISSUE TITLE
Bitcoin Bridge Implementation

### ISSUE THREAD

**Issue by j0j0r0** [dragonchain/dragonchain#25]
Implement a bridge to allow interaction between Bitcoin and internal currencies.

Need ability to track addresses (internal and external will be Bitcoin addresses) and fire events based upon activity.

Need ability to create Bitcoin transactions and broadcast to Bitcoin network.

Will probably involve integration of open source bitcoin wallet software.

**Comment by wolfpack94** [comment]
`thrift`
struct public_proof {
   1: VerificationRecord verification_record
}

**Comment by wolfpack94** [comment]
`struct public_proof {
     1: VerificationRecord verification_record
  }`

**Comment by wolfpack94** [comment]
I modified the verification_info created in _execute_timestamping so that the json struction now looks like this, 
`verification_info = {`
`         verification_records = {`
`                   origin_id = {`
`                              verification_id = hash`
`                   }`
`          }`
`}`

is that what you were talking about on Thursday @j0j0r0 ?

**Comment by j0j0r0** [comment]
Yes, exactly. 
:)

**Comment by j0j0r0** [comment]
Although you may have to refresh my memory about the outer verification_info...

**Comment by wolfpack94** [comment]
Updated the code snippet to the full `verification_info` structure as it stands now in the code.

**Comment by wolfpack94** [comment]
@j0j0r0 @Voxelot Can this be closed since it was merged?
