### ISSUE TITLE
Move lower phase hash to top level parameter in sign_verification_record

### ISSUE THREAD

**Issue by j0j0r0** [dragonchain/dragonchain#8]
Currently the `lower phase hash` is included in the verification record via inclusion in the `verification_info` parameter.

Since this is important to the architecture and consensus, it _should_ be given a more explicit position in the signing process.

**Comment by micylt** [comment]
`lower_phase_hash` is now included as a top level parameter in `sign_verification_record`. Also being appended to hashed_items separately from `verification_info`.

`phase_1` lower phase hash is being set to 0 since there's not a phase lower than `phase_1`.
`phase_3`  is keeping the list of `phase_2` `lower_phase_hashes` in addition to creating a separate `lower_phase_hash` from the hash of `lower_phase_hashes`,  which is included as a top level parameter.
--Took note to consider storing a structure of (`signatory`, `hash`) rather than `lower_phase_hashes` in `phase_3`.

Ran and tested the code after making the changes through `phase_4` without issues.

**Comment by micylt** [comment]
Reclose after merging with master.

**Comment by j0j0r0** [comment]
Merged w/PR #12
