### ISSUE TITLE
Subscription Feed

### ISSUE THREAD

**Issue by micylt** [dragonchain/dragonchain#86]
Allow ability for node subscription in network configuration.

**Comment by micylt** [comment]
@j0j0r0 and @Voxelot please input your thoughts on this.

**Comment by j0j0r0** [comment]
We need to allow a criteria in the request or configuration.

A node should be able to set criteria for the following:

- transaction type
- actor
- business_unit
- entity?
- family_of_business
- line_of_business
- owner
- verification level
- block depth (how many blocks have passed at the verification level)

Not all of these need to be available in the first pass.

[More to come]

**Comment by micylt** [comment]
I believe we will also want to specify the host/port of the subscribee in the request in the case a connection has not yet been established.

**Comment by j0j0r0** [comment]
Yes, should be treated as another discovery method I guess.

The new node should be added to the network/nodes table and included with a high priority (or is there a way to require/guarantee that it will be added in that table?).

**Comment by j0j0r0** [comment]
# Notes from conversation between @micylt and @j0j0r0:

- [ ] Both nodes will store the subscription info (criteria, auth, etc.)
- [ ] The subscription will be assigned an ID (either from the client/subscriber or the server/subscribee [preferred]).
- [ ] A cron service will be set for every 5 seconds to call the sub process and check if there are any subscriptions to execute
- [ ] The sub process will go through the `subscriptions` table to see if any need to be called
- [ ] The `subscriptions` table will need to have a `last_time_called` field so that the sub process will know if a subscription should be executed _(`now` - `last_time_called` > `period/seconds_between_calls`)_
- [ ] The subscription will be called (via Thrift) per the period requested in the sub info (secs between sync)
- [ ] When calling the subscription thrift service, only (1) the sub ID and (2) latest/min block will be sent.
- [ ] The subscribing node (the client) will maintain the latest/min block info and increment it appropriately when it receives new transactions

## Provisioning

- The provisioning process will require the admin to send to the sub node a request with the subscription info in a transaction signed by the admin(s)
- The node will sign and send request containing this info to the server/subscribee node which will start an auth process (TBD)
  1. manual authorization given by maintaining admins via transaction
  1. manual authorization given by maintaining admins via web interface
  1. custom / automated smart contract based authorization (TBD)
- both nodes will hold the sub info in a `subscription` table (with criteria, ID, public keys [both nodes keys], etc.)

**Comment by j0j0r0** [comment]
## Phases of implementation

We should build this in 3 phases:

1. Subscription communication (manual database entry of subscriptions)
1. Provisioning (simple implementation of provisioning via transaction)
1. Authentication and Authorization - checking the following:
   - signing of provisioning transaction
   - signing of Thrift message from client node
   - signing of each sub request (by subscriber) and response (by subscribee)

**Comment by j0j0r0** [comment]
The response of any given sub call should limit transactions to a reasonable number and allow pagination.

In the future this same mechanism can be used to gather historical records from a node by starting at `block_id` `0` and paging through responses until the current block.

**Comment by j0j0r0** [comment]
## Database

Create tables for both client and server function.

### Client

| Field        | Type           | Notes |
| ------------- |-------------|-------------|
| _**subscription_id**_      | UUID | PK |
| _**subscribed_node_id**_     | _**UUID**_   |**@micylt in your doc you had this as VARCHAR(256)**   |  
| host | character varying (256)      |   |
| port | _**Integer**_      | **@micylt in your doc you had this as VARCHAR also**  |
| criteria | json      |   |
| minimum_block_id | Integer      |   |
| _**synchonization_period**_ | Integer      |   |

_**^ Bold and italicized are recommended changes**_

### Server

| Field        | Type           | Notes |
| ------------- |-------------|-------------|
| subscriber_id | UUID      |   |
| criteria | json      |   |
| subscriber_public_key | VARCHAR(n)      |   |

**Comment by j0j0r0** [comment]
For authentication on each query, the client will hash the criteria, and certain components of the request (e.g. min block ID), and sign that, passing this signature.

The server will take the subscription ID, retrieve the record, hash the criteria that it knows, and the request information, and validate the signature for authentication before executing the query.

**Comment by j0j0r0** [comment]
Per discussion at dev meeting on 2017-01-11...

A subscribing node (client) should aggregate sub queries and send only one request per round to each serving node.

The criteria field in the query/request should be an array (optional?) of JSON criteria structures.

The server should execute all criteria, deduplicate the results and return the entire set/array.

**Comment by j0j0r0** [comment]
Question: Does the client node need to have access to the verification records for all returned transactions?
Probably yes.

If so, how best to get them back?
I'm assuming that they would ride alongside the transactions in a separate field in response.

`
{
  transactions: [
  ],
  verification_records: [
  ]
}

@micylt @Voxelot thoughts?

**Comment by Voxelot** [comment]
I'd like to maintain the separation of transaction data <-> subscription feeds && verification data <-> receipts if possible.

The simplest way is to build upon what we've already done. When the client polls for subscription feed data, insert vr_transfer records on the server (with transfer_to set as the requesting client node ID) for each verification record with origin == server.id && block id > minimum block id in the request.

Make sense?

**Comment by j0j0r0** [comment]
@Voxelot I do understand and would be open to discussion, but in that case, I wouldn't like the separation of the subscription specific verification record (VR) from the transactions themselves as I think that we want/need to validate that the transactions are included w/in the necessary VR before we store and trust them (either check that they were contained within VR up to the required phase from the query criteria or if not specified, contained w/in a phase 1 VR from the subscribed node.

While it may be more efficient and clean from the perspective of the channels over which the data flows (i.e. **VR** and **transactions** respectively separated), we would be separating the subscribed transactions from the VR that will allow the client to verify them as part of the processing that occurred.

I think that It would be simpler to implement a check/validation function before we store the transactions if the VR are in the response.

I prefer to think of the 2 channels as transferring data for specific use [1] broadcast receipt/sync and [2] transaction subscription data feed rather than purely what is or should be sent over them.

We also need to discuss how to get the other later VR back to the client node. That is, if a node subscribes to P2 verified transactions of transaction_type X...

- How does that node get updates to the verification state?
- Does it need to get updates?
- Would it be sufficient to require the client to specifically request updates if there is a business need?

I would lean right now to including the VR within the response so that the client has a self contained answer in one step with all of the information that it needs to validate the received data, and that only the minimum VR records would be contained per the specified criteria. If the client has a need to request newer or higher VR, it can do so explicitly. Whether that is another Thrift service or an override (preferred) of the existing VR `transfer_data` is an open question.

Thoughts?

**Comment by Voxelot** [comment]
@j0j0r0 I see the advantages to your approach. From an integration perspective, it would simplify applications that rely on subscriptions to have all the verifications required in the criteria locally available as soon as the transactions are received. Especially if there are many peers or long network delays between making two separate calls for different datatypes.

I'm wondering if maybe using another table similar to `vr_transfers` would solve some of these concerns. We could have a subscription table called `subscription_transfers` to tag which blocks are of interest to whom. Perhaps we make receiving all verification records a subscription criterion? As blocks are transferred to the client, the server would add an entry to the subscription transfers table containing the client id and the block id. When server receives other later verification records after the block was already transferred, we could extend the replication logic in `resolve_data` to see if the verification belongs to any blocks in the `subscription_data` table that were marked as already transferred. For each row returned, insert a `vr_transfer` record with the `transfer_to` field set as the subscription client ID to be picked up by the data synchronization process later.

There may be benefits to extending this subscription transfers table approach further. Servers could proactively insert records into this table as it processes transactions and mark blocks as unsent and criteria unmet. This would provide us with a fast lookup when verifications are received by the server for any particular block id to determine if the criteria has been satisfied yet, and if the block (txn + vr data) is ready to be transmitted. This amortizes the cost of computing subscription criteria and caches the results, making the polling calls from clients very lightweight (and more DOS resilient). Once the client polls for subscription data, we'd return any blocks flagged as ready (in order without breaking continuity) for that client and mark them sent. This avoids the need for clients to keep track of block ids and ensures all data that meets the subscription criteria is received. Pagination is simple, as each page of block data would be marked as 'sent' so it isn't transmitted again. The table is fairly light and would only consume a couple MB per subscription with regular cleanup tasks.

Here's a start on some of the fields I think we'd need for a full-blown `subscription_transfers` table:
```
BEGIN;
/* Don't drop tables unless you really want to */
CREATE TABLE IF NOT EXISTS subscription_transfers (
    transfer_id UUID PRIMARY KEY,
    /* Original owner of the transaction data (Blockchain ID) */
    subscription_id UUID,
    /* The node to transmit this block to */
    client_id VARCHAR(256),
    /* block id */
    block_id INT,
    /* Indicates whether the subscription criteria for this block is satisfied */
    criteria_met BOOLEAN DEFAULT FALSE,
    /* Indicates whether a block has been transmitted or not */
    sent BOOLEAN DEFAULT FALSE
);
COMMIT;
BEGIN;
GRANT ALL ON subscription_transfers to blocky;
COMMIT;

/* used to accelerate queries from subscription clients for blocks that are ready to transfer */
BEGIN;
CREATE INDEX subscription_transfers_rdy_to_transfer_idx ON subscription_transfers (client_id, criteria_met, sent);
COMMIT;

/* used to accelerate queries when verification records are received to see if criteria has been satisfied */
BEGIN;
CREATE INDEX subscription_transfers_criteria_check_idx ON subscription_transfers (block_id, criteria_met);
COMMIT;
```

Whenever the server receives a verification record that has an origin id == it's own node id, it could run the following lookup query to run the criteria validation and update any transfer ids with `criteria_met=true` if the subscription criteria is satisfied:
```
/* retrieve of a list of subscription ids to verify criteria against */
SELECT * FROM subscription_transfers WHERE block_id = <VERIFICATION.block_id> AND criteria_met = FALSE;
```

When the client makes a request for subscription data, the server could run the following query to determine which blocks to transfer (make limit configurable):
```
/* client request for blocks that are ready to transfer */
SELECT * FROM subscription_transfers
    WHERE client_id=<CLIENT_ID>
    AND criteria_met = TRUE
    AND sent = FALSE
    /* return blocks in order from lowest, up until there is a block not ready for transfer */
    AND block_id < COALESCE((SELECT block_id FROM subscription_transfers
                                                                  WHERE client_id=<CLIENT_ID>
                                                                  AND criteria_met = FALSE
                                                    ORDER BY block_id ASC LIMIT 1), 2147483647)
ORDER BY block_id ASC LIMIT 10;

```

Some additional thought would be needed as far as handling of historical data with this approach. Maybe that could be a handled via a separate API that functions more like the original idea of passing a starting block id to avoid overloading this table with too much data. Or maybe you simply pass in a starting block id to an API that kicks off a cron to build up the `subscription_transfers` table from that point onwards. 

This might be overkill if we don't require later verifications beyond what's required in the subscription criteria, and if we have a way to build efficient SQL queries out of subscription criteria to find transactions and verification records of interest. Thoughts?

**Comment by j0j0r0** [comment]
I really like the idea of adding criteria for handling VR. Probably with options:

- No VR
- Proof - Only deliver VR necessary to prove the presence of the returned transactions within the highest phase asked for within the criteria (Phase 1 if no phase criteria specified)
- All existing VR

And then allow the client to request further VR if wished.

I certainly wouldn't mind the secondary table to track comms of the VR blocks, but I think that I'll want the transactions to be placed into the main `transactions` table so that queries can be seamless no matter the source of the data.

1. Should that apply as well to the VR? Ideally, I think so.
1. Should the actual VR be transferred into the main `verification_records` table, while the `subscription_transfers` table holds the tracking info? 
1. or could the `subscriptions` table be used to extrapolate that function (using the VR transfer criteria)?

We can get together to discuss if that makes sense as there's a lot here.

**Comment by j0j0r0** [comment]
Just spoke with @Voxelot - we're totally on the same page now.

Basically:

- All currently available VR will come along with the transactions
- Server will track each block with the `subscription_transfers` table for updates on those blocks (details to come)
- We'll not have a bunch of options for _new_ VR, but instead just provide the client with all to come
- We'll have a criteria for whether you want all applicable historical data or just from this point on (we have a design for how that works in the `subscription_transfers` table

He'll be writing up notes for the implementation!
:)

**Comment by j0j0r0** [comment]
New considerations after discussion with @micylt 

Since the client (subscribing) node will not in most any circumstance have a broadcast/consensus connection with the server node, it seems unreasonable to have the VR transfer via the broadcast receipt pipe (that would seem to require that we add an arbitrary connection and another step to that process).

Rather, if we were to create the `subscription_transfers` table as described above (rename to subscription vr backlog) and store any block id that is of interest to the subscription (i.e. that has a transaction that meets the criteria of the subscription). 

When the server node gets any VR from broadcast receipt process, it will check this table to see if that block id is in the table and if so will copy the VR to the `vr_transfers` (correct name?) table. 

When a subscription call is handled on the server, the sub query will be executed, any results added to the structure defined above (transactions list + VR list) and then look within the `vr_transfers` table for any VR with a `transfer_to` matching the client ID of the client/subscriber and add these as a list of VR within the response.

**Comment by j0j0r0** [comment]
Also I think that `criteria_met` in `subscription_transfers`should be renamed to something like `completion_criteria` and should contain json criteria for removing the row as complete (i.e. When all VR have been transferred to the subscriber) (e.g. Phase=5).

`sent` field eliminated(?) as when completion criteria is met, row should be deleted.

**Comment by Voxelot** [comment]
Ah right, the broadcast receipts would only work between subscribed nodes if they're both running phase 2+.  This approach of adding the sub-query to the vr_transfers table when subscriptions are called makes sense.

The purpose of the `sent` flag was to prevent resending transactions after they've already been transferred. Also, without the `sent` flag we'd run the risk of transmitting verification records for the block before it's criteria has been satisfied. My idea was that verifications should only be added to `vr_transfers` to pick up stragglers that didn't make it into the initial transfer of the block.

What's the main difference between the `completion_criteria` field and the criteria on the subscription? Would it vary from block to block for a particular subscription? I like the idea of having these records auto-cleanup, but the meaning of `completion_criteria` for cleanup seems different than using `criteria_met` for indicating that a block has met some minimum level of validation required and is ready to be transferred.

Without the `criteria_met` flag, we'd also need to re-evaluate the subscription criteria per block, every time the client polls for available blocks. This seems suboptimal compared to the server only needing to check the subscription criteria as it receives verifications for that specific block, and then simply return the blocks marked as ready to transfer when the client requests them.

**Comment by j0j0r0** [comment]
OK - my thought on the `sent` flag was that the row wouldn't be placed in the `subscription_transfers` table until the sub criteria was met and the transactions and initial/available VR were sent to the subscriber - the row's existence would be the equivalent of this flag.

RE: `completion_criteria`, it _would_ be different than the sub criteria in that it would define when we will stop sending VR to the subscriber. For now, we could default/hard-code it to stop after level 5 is attained, and ideally or later, the client could specify in the sub criteria what this should be.

We will need to execute the criteria for whether new transactions (and wrapping VR) need to be sent to the subscriber every time, and if we are placing VR within the vr_transfers table as they arrive based upon the `subscription_transfers` rows, then the query for outstanding VR for the subscription is simple as well.

The `criteria_met` I think is not needed, as if the row is present, then the criteria has already been met for the transactions of that block, the initially available VR were transferred, and any other VR that come in for that block will be placed into the VR transfers table to move in subsequent subscription request calls from the client.

**Comment by j0j0r0** [comment]
Let me know @micylt if you need a stepwise process.

Otherwise, use what's in my comment above...
https://github.com/dragonchain/dragonchain/issues/86#issuecomment-274015652

**Comment by Voxelot** [comment]
So rather than evaluating the subscription criteria for a block when associated txns and verifications are processed and received by the server, we'll evaluate the criteria when the client makes a request for subscription data and then insert a record into the `subscription_transfers` table when the criteria is satisfied? As long as the subscription criteria is simple enough to convert into lightweight queries, this does seem like a more space efficient approach.

My main reason for asking whether the `completion_criteria` would vary from block to block is that it seems like it would be mostly redundant data that could've been derived from the subscription criteria. Is this something that should be put into the server subscription table and stored once per subscription instead of each block for each subscription?

**Comment by j0j0r0** [comment]
True about completion criteria, but if it were stored in subs table then the process that is looking at the sub transfers table (when new VR arrive) would have to also query the subs table. 

My thought is that it'll be simplest here as it will be a part of the query criteria JSON, and thus not efficiently available from the subscriptions table.

**Comment by j0j0r0** [comment]
Per design discussion today...

Create a new `sub_transfers` table to hold all components of a response (transactions & VR).

Move query execution to within the broadcast receipt processing.

Upon broadcast receipt of VR...

1. Check if that block is marked with a record in the `sub_vr_backlog` table - if it is, then we've already matched criteria and need to add this VR to the `sub_vr_table` for transfer to the client - processing complete.
1. Check if there are any active subscriptions that have phase criteria that match this VR phase (e.g. vr == 3). If so, then execute the subscription query criteria against the transactions in that block (and only that block). If any are matched, then build a response record with matching transactions, and all existing VR for that block, and add to the `sub_vr_table` for transfer to the client (at the next sub service call). Also add a record to the `sub_vr_backlog` table.

When the client calls the subscription service (periodically), the server will only query the `sub_vr_table` for any rows matching client node ID == transfer_to.

@micylt let me know if I missed anything in the above description.

**Comment by micylt** [comment]
@j0j0r0 I like this approach. Thank you.

**Comment by Briechenstein12** [comment]
#105 Subscription Feed
